### ISSUE TITLE
remove ``webstomp-client`` and use ``sockjs-client`` api directly

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-client#153]
- remove ``webstomp-client`` - support discontinued 
- use [sockjs-client](https://www.npmjs.com/package/sockjs-client) lib api
- upgrade sockjs-client to the lates version

**Comment by rmmayo** [comment]
https://www.dariawan.com/tutorials/spring/create-spring-boot-websocket-app-using-stomp-and-sockjs/

**Comment by rmmayo** [comment]
it looks like the [example](https://www.dariawan.com/tutorials/spring/create-spring-boot-websocket-app-using-stomp-and-sockjs/) we looked at is using `stomp-websocket` instead of `webstomp-client`.  Both of these libs are ~3 years old and no longer seem to be maintained, and I think that `webstomp-client` evolved from `stomp-websocket` - he references it [here](https://www.npmjs.com/package/webstomp-client#api).

[stomp-websocket](https://www.npmjs.com/package/stomp-websocket)
[webstomp-client](https://www.npmjs.com/package/webstomp-client)

After further digging, I believe we want to use [stompjs](https://www.npmjs.com/package/@stomp/stompjs)

**Comment by rmmayo** [comment]
@sudo-may testing out [stompjs](https://www.npmjs.com/package/@stomp/stompjs)....seems much faster to setup the initial, but after several attempts I was able to report a skill prior to the websocket connection being fully established:

![image](https://user-images.githubusercontent.com/47030042/131490356-26c78ecc-d56e-45cb-8866-a19643db2179.png)

**Comment by rmmayo** [comment]
> @sudo-may testing out [stompjs](https://www.npmjs.com/package/@stomp/stompjs)....seems much faster to setup the initial, but after several attempts I was able to report a skill prior to the websocket connection being fully established:
> 
update, the previous screenshot was done using Spring's built in simple message broker, when testing using rabbitmq the messages are delivered even if the skill was reported before the connection was fully established.

![image](https://user-images.githubusercontent.com/47030042/131499101-9161818b-1aa6-487c-9e8e-f56708ec0366.png)
