### ISSUE TITLE
Skilltree as LMS

### ISSUE THREAD

**Issue by koff75** [NationalSecurityAgency/skills-client#172]
Hello, I fell in love with the Skilltree gamification tool which after testing it, is very well developed.
I'm looking to put forward cybersec awarness modules through Skilltree...
Currently, I don't have a learning platform, and then I'm starting from scratch;
Do you think it's could be possible to use Skilltree directly as an LMS and put my modules content in the Skilldisplay ? Or do I need to develop an LMS platform (could be with Wordpress or NextJS) and integrate the Skilltree API on each completion button call ?

Thanks :)

**Comment by sudo-may** [comment]
@koff75 Thank you for the kind words! It really depends on the type and the amount of the training/instructions that you plan to have. If you think skills' description will suffice for your modules content then SkillTree as an LMS would work (via Progress and Ranking views paired with SkillTree's self-reporting capabilities). Otherwise integrating SkillTree API into your LMS platform would work well! Hope this helps!

**Comment by koff75** [comment]
Thanks for your answer, it's clear now :)
